// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmgrmpjgcoyukwcabgcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ3JtcGpnY295dWt3Y2FiZ2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTY4MDYsImV4cCI6MjA3MjgzMjgwNn0.SMBVj9SeAFYu803ATMp6kt7x60V645lDzXxfcxX_zSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});